sudo: required
dist: jammy
services:
  - xvfb
addons:
  chrome: stable

language: node_js
node_js:
  - "20"
cache:
  directories: node_modules
before_script:
  - npm cache clean --force
  - npm install
script:
  - npm run build
