sudo: required
dist: jammy
services:
  - xvfb
addons:
  chrome: stable

language: node_js
node_js:
  - "20"
  - "17"
  - "16"
cache:
  directories: node_modules

before_script:
  - npm rebuild node-sass

script:
  - npm run build
